import table1 from "./Images/table-1.jpg";
import table2 from "./Images/table-2.jpg";
import table3 from "./Images/table-3.jpg";

export const products = [
  {
    title: "Product name",
    description: "Description",
    category: "Category",
    subcategory: "Subcategory",
    roomCategory: "Room",
    isNew: false,
    discount: 0,
    price: 0,
    oldPrice: 0,
    isLiked: false,
    isBought: false,
    photo: "url",
    photoSet: ["url", "url", "url"],
  },
  {
    title: "Product name",
    description: "Description",
    category: "Category",
    subcategory: "Subcategory",
    roomCategory: "Room",
    isNew: false,
    discount: 0,
    price: 0,
    oldPrice: 0,
    isLiked: false,
    isBought: false,
    photo: "url",
    photoSet: ["url", "url", "url"],
  },
  {
    title: "Product name",
    description: "Description",
    category: "Category",
    subcategory: "Subcategory",
    roomCategory: "Room",
    isNew: false,
    discount: 0,
    price: 0,
    oldPrice: 0,
    isLiked: false,
    isBought: false,
    photo: "url",
    photoSet: ["url", "url", "url"],
  },
  {
    title: "Product name",
    description: "Description",
    category: "Category",
    subcategory: "Subcategory",
    roomCategory: "Room",
    isNew: false,
    discount: 0,
    price: 0,
    oldPrice: 0,
    isLiked: false,
    isBought: false,
    photo: table1,
    photoSet: [table1, table2, table3],
  },
  {
    title: "Product name",
    description: "Description",
    category: "Category",
    subcategory: "Subcategory",
    roomCategory: "Room",
    isNew: false,
    discount: 0,
    price: 0,
    oldPrice: 0,
    isLiked: false,
    isBought: false,
    photo: table1,
    photoSet: [table1, table2, table3],
  },
  {
    title: "Product name",
    description: "Description",
    category: "Category",
    subcategory: "Subcategory",
    roomCategory: "Room",
    isNew: false,
    discount: 0,
    price: 0,
    oldPrice: 0,
    isLiked: false,
    isBought: false,
    photo: table1,
    photoSet: [table1, table2, table3],
  },
  {
    title: "Product name",
    description: "Description",
    category: "Category",
    subcategory: "Subcategory",
    roomCategory: "Room",
    isNew: false,
    discount: 0,
    price: 0,
    oldPrice: 0,
    isLiked: false,
    isBought: false,
    photo: table1,
    photoSet: [table1, table2, table3],
  },
  {
    title: "Product name",
    description: "Description",
    category: "Category",
    subcategory: "Subcategory",
    roomCategory: "Room",
    isNew: false,
    discount: 0,
    price: 0,
    oldPrice: 0,
    isLiked: false,
    isBought: false,
    photo: "url",
    photoSet: ["url", "url", "url"],
  },
];
